name: Extract HREFs via API

on:
  repository_dispatch:
    types: [extract-hrefs]

jobs:
  run-reusable-workflow:
    uses: ./.github/workflows/extract_hrefs.yml
    with:
      urls: ${{ toJson(github.event.client_payload.urls) }}
    secrets: inherit
